/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.DoctorRole;

import Business.Enterprise.Enterprise;
import Business.Patient.Patient;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.UserPriviligeWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;

/**
 *
 * @author hpanjwani
 */
public class SendLabTestPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private Enterprise enterprise;
    
    private Patient patient;
    private String disease;

    /**
     * Creates new form SendLabTestPanel
     */
    public SendLabTestPanel(JPanel userProcessContainer, UserAccount userAccount, Enterprise enterprise, Patient patient) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.enterprise = enterprise;
        this.patient = patient;
        
        disease = patient.getDisease();
        
        docLabel.setText("Doctor Name  Dr. " + userAccount.getUsername());
        patientLabel.setText("Patient Name: " + patient.getName());
        diseaseLabel.setText("Symptoms suggest you have : " + this.disease);
        
        populateLabTestTable();
    }

    public void populateLabTestTable() {
        
        DefaultTableModel model = (DefaultTableModel) labTestTable.getModel();
        model.setRowCount(0);

        for (WorkRequest request : userAccount.getWorkQueue().getWorkRequestList()) {
            if ((request.getStatus().equals("Pending Test")) || (request.getStatus().equals("Processing Test"))
                    || (request.getStatus().equals("Test Completed"))) {
            if (((UserPriviligeWorkRequest) request).getPatient().equals(patient)) {
//
//                Patient patient = (Patient) ((UserPriviligeWorkRequest) request).getPatient();

                //int size = patient.getDonationList().size() - 1;
//                if(size < 0)   {
//                    break;
//                }
//                else    {
                Object[] row = new Object[8];

                row[0] = request;
                row[1] = request.getSender();
                row[2] = request.getReceiver();
                row[3] = ((UserPriviligeWorkRequest) request).getPatient();
                row[4] = request.getRequestDate();
                row[5] = request.getResolveDate();
                String result = ((UserPriviligeWorkRequest) request).getTestResult()== null ? null : ((UserPriviligeWorkRequest) request).getTestResult();
                row[6] = result;
                row[7] = request.getStatus();
                
//                    row[5] = request.getResolveDate();
//                    String result = ((LabTestWorkRequest) request).getTestResult();
//                    row[6] = result == null ? "Waiting" : result;
//                    
//                    if(result != null)    {
//                        for(int j = 0; j < d.getDonationList().size(); j++)   {
//                            if(d.getDonationList().get(j).equals(result))   {
//                                size  = j;
//                                System.out.println(size);
//                                break;
//                            }
//                        }
//                    }
//                    
//                    int unit = d.getDonationList().get(size).getUnit();
//                    row[7] = String.valueOf(unit) == null ? "Waiting" : String.valueOf(unit);

                model.addRow(row);
                }
            }
            //}
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        labTestTable = new javax.swing.JTable();
        backBtn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        docLabel = new javax.swing.JLabel();
        patientLabel = new javax.swing.JLabel();
        diseaseLabel = new javax.swing.JLabel();

        labTestTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Test", "Doctor Name", "Lab Assistant", "Patient Name", "Request Date", "Resolve Date", "Result", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        labTestTable.setToolTipText("List of Lab Test Request");
        labTestTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labTestTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(labTestTable);

        backBtn.setText("<< Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel6.setText("Lab Test Requests");

        docLabel.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        docLabel.setText("<doctorName>");

        patientLabel.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        patientLabel.setText("<patientName>");

        diseaseLabel.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        diseaseLabel.setText("<disease>");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(259, 259, 259)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(docLabel)
                            .addComponent(patientLabel)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(diseaseLabel))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addComponent(jLabel6))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(backBtn, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 586, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(360, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(docLabel)
                .addGap(18, 18, 18)
                .addComponent(patientLabel)
                .addGap(18, 18, 18)
                .addComponent(diseaseLabel)
                .addGap(72, 72, 72)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(backBtn)
                .addContainerGap(165, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backBtnActionPerformed

    private void labTestTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labTestTableMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_labTestTableMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel diseaseLabel;
    private javax.swing.JLabel docLabel;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable labTestTable;
    private javax.swing.JLabel patientLabel;
    // End of variables declaration//GEN-END:variables
}
