/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.DoctorRole;

import Business.Business;
import Business.Enterprise.Enterprise;
import Business.Patient.Patient;
import Business.Patient.VitalSign;
import Business.Patient.VitalSignHistory;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.UserPriviligeWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author hpanjwani
 */
public class SymptonsPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private WorkRequest request;
    private Enterprise enterprise;
    private Business business;
    
    private Patient patient;
    private String disease = null;
    /**
     * Creates new form SymptonsPanel
     */
    public SymptonsPanel(JPanel userProcessContainer, UserAccount account, Enterprise enterprise, Business business, WorkRequest request) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.request = request;
        this.enterprise = enterprise;
        this.business = business;
        
        patient = (Patient)((UserPriviligeWorkRequest) request).getPatient();
        
        doctorLabel.setText("Doctor Name  Dr. " + userAccount.getUsername());
        patientLabel.setText("Patient Name  Mr. " + ((UserPriviligeWorkRequest) request).getPatient().getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        malariaRadioBtn = new javax.swing.JRadioButton();
        dengueRadioBtn = new javax.swing.JRadioButton();
        typhoidRadioBtn = new javax.swing.JRadioButton();
        jaundiceBtn = new javax.swing.JRadioButton();
        diabetesRadioBtn = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        nextBtn = new javax.swing.JButton();
        doctorLabel = new javax.swing.JLabel();
        patientLabel = new javax.swing.JLabel();

        buttonGroup1.add(malariaRadioBtn);
        malariaRadioBtn.setText("Fever, Chills, Headache, Sweats, Fatigue, Nausea, Vomiting");
        malariaRadioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                malariaRadioBtnActionPerformed(evt);
            }
        });

        buttonGroup1.add(dengueRadioBtn);
        dengueRadioBtn.setText("Sudden high fever, Severe headaches, Severe joint and muscle pain");
        dengueRadioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dengueRadioBtnActionPerformed(evt);
            }
        });

        buttonGroup1.add(typhoidRadioBtn);
        typhoidRadioBtn.setText("Poor appetite, Headaches, Generalized aches and pains, Lethargy, Diarrhea");
        typhoidRadioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typhoidRadioBtnActionPerformed(evt);
            }
        });

        buttonGroup1.add(jaundiceBtn);
        jaundiceBtn.setText("Fatigue, Nausea, Loss of appetite, Yellowing of the eyes and skin");
        jaundiceBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jaundiceBtnActionPerformed(evt);
            }
        });

        buttonGroup1.add(diabetesRadioBtn);
        diabetesRadioBtn.setText("Increased thirst, Frequent urination, Hunger, Fatigue, Blurred vision");
        diabetesRadioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diabetesRadioBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setText("SYMPTOMS");

        backBtn.setText("<< Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        nextBtn.setText("Next >>");
        nextBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextBtnActionPerformed(evt);
            }
        });

        doctorLabel.setText("<doctorName>");

        patientLabel.setText("<patientName>");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(360, 360, 360)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jaundiceBtn)
                            .addComponent(diabetesRadioBtn)
                            .addComponent(malariaRadioBtn)
                            .addComponent(dengueRadioBtn)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(backBtn)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(nextBtn))
                                .addComponent(typhoidRadioBtn))
                            .addComponent(doctorLabel)
                            .addComponent(patientLabel))))
                .addContainerGap(415, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(doctorLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(patientLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(malariaRadioBtn)
                .addGap(18, 18, 18)
                .addComponent(dengueRadioBtn)
                .addGap(18, 18, 18)
                .addComponent(typhoidRadioBtn)
                .addGap(18, 18, 18)
                .addComponent(jaundiceBtn)
                .addGap(18, 18, 18)
                .addComponent(diabetesRadioBtn)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backBtn)
                    .addComponent(nextBtn))
                .addGap(45, 45, 45))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nextBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextBtnActionPerformed
        // TODO add your handling code here:
        
        if(disease == null)   {
            JOptionPane.showMessageDialog(this, "Please select one sympton!", "WARNING", JOptionPane.WARNING_MESSAGE);
            return;
        }
        else if(disease.equals("Diabetes")) {
            ReferDoctorPanel referDoctorPanel = new ReferDoctorPanel(userProcessContainer, userAccount, request, enterprise, business, patient, disease);
            userProcessContainer.add("ReferDoctorPanel", referDoctorPanel);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        }
        else    {
            PrescriptionPanel processRequestPanel = new PrescriptionPanel(userProcessContainer, userAccount, request, enterprise, disease);
            userProcessContainer.add("ProcessRequestPanel", processRequestPanel);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        }
    }//GEN-LAST:event_nextBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        
        VitalSignHistory vitalSignHistory = patient.getVitalSignList();
        int size = vitalSignHistory.getVitalSignList().size();
        
        VitalSign vs = vitalSignHistory.getVitalSignList().get(size - 1);
        
        vitalSignHistory.getVitalSignList().remove(vs);
        
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backBtnActionPerformed

    private void malariaRadioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_malariaRadioBtnActionPerformed
        // TODO add your handling code here:
        if(malariaRadioBtn.isSelected())
            disease = "Malaria";
    }//GEN-LAST:event_malariaRadioBtnActionPerformed

    private void dengueRadioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dengueRadioBtnActionPerformed
        // TODO add your handling code here:
        if(dengueRadioBtn.isSelected())
            disease = "Dengue";
    }//GEN-LAST:event_dengueRadioBtnActionPerformed

    private void typhoidRadioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typhoidRadioBtnActionPerformed
        // TODO add your handling code here:
        if(typhoidRadioBtn.isSelected())
            disease = "Typhoid";
    }//GEN-LAST:event_typhoidRadioBtnActionPerformed

    private void jaundiceBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jaundiceBtnActionPerformed
        // TODO add your handling code here:
        if(jaundiceBtn.isSelected())
            disease = "Jaundice";
    }//GEN-LAST:event_jaundiceBtnActionPerformed

    private void diabetesRadioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diabetesRadioBtnActionPerformed
        // TODO add your handling code here:
        if(diabetesRadioBtn.isSelected())
            disease = "Diabetes";
    }//GEN-LAST:event_diabetesRadioBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton dengueRadioBtn;
    private javax.swing.JRadioButton diabetesRadioBtn;
    private javax.swing.JLabel doctorLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jaundiceBtn;
    private javax.swing.JRadioButton malariaRadioBtn;
    private javax.swing.JButton nextBtn;
    private javax.swing.JLabel patientLabel;
    private javax.swing.JRadioButton typhoidRadioBtn;
    // End of variables declaration//GEN-END:variables
}
