/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.DiabeteRole;

import Business.Enterprise.Enterprise;
import Business.Medicine.Medicine;
import Business.Patient.Appointment;
import Business.Patient.Patient;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Color;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author hpanjwani
 */
public class InsulinMedicationPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private Enterprise enterprise;

    private Patient patient;
    private String diabeteLevel;
    private Appointment appoint;

    /**
     * Creates new form InsulinMedicationPanel
     */
    public InsulinMedicationPanel(JPanel userProcessContainer, UserAccount account, Enterprise enterprise, Patient patient, String level) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.enterprise = enterprise;

        this.patient = patient;
        this.diabeteLevel = level;

        hospitalName.setText("Hospital Name: "  + enterprise.getName());
        docLabel.setText("Doctor Name: " + userAccount.getUsername());
        patientLabel.setText("Patient Name: " + patient.getName());
        diseaseLabel.setText("Symptons suggest you have: " + diabeteLevel);
        
        nextBtn.setEnabled(false);

        if (diabeteLevel.equals("Type 1")) {
            this.patient.setDisease("Diabetes Type I");
            diseaseLabel.setText("Symptoms suggest you have : Diabetes Type I ");
        } else if (diabeteLevel.equals("Type 2")) {
            this.patient.setDisease("Diabetes Type II");
            diseaseLabel.setText("Symptoms suggest you have : Diabetes Type II ");
        }

        populateComboBox();
    }

    public void populateComboBox() {
        medComboBox.removeAllItems();
        medComboBox2.removeAllItems();
        medComboBox3.removeAllItems();
        medComboBox4.removeAllItems();

        if (diabeteLevel.equals("Type 1")) {

            medComboBox.addItem("Apidra");
            medComboBox.addItem("Humalog");
            medComboBox.addItem("Humulin N");
            medComboBox.addItem("Lantus");

            medComboBox2.addItem("Apidra");
            medComboBox2.addItem("Humalog");
            medComboBox2.addItem("Humulin N");
            medComboBox2.addItem("Lantus");

            medComboBox3.addItem("Apidra");
            medComboBox3.addItem("Humalog");
            medComboBox3.addItem("Humulin N");
            medComboBox3.addItem("Lantus");

            medComboBox4.addItem("Apidra");
            medComboBox4.addItem("Humalog");
            medComboBox4.addItem("Humulin N");
            medComboBox4.addItem("Lantus");

        } else if (diabeteLevel.equals("Type 2")) {

            medComboBox.addItem("Velosulin BR");
            medComboBox.addItem("Levemir");
            medComboBox.addItem("Iletin Lente");
            medComboBox.addItem("ReliOn");

            medComboBox2.addItem("Velosulin BR");
            medComboBox2.addItem("Levemir");
            medComboBox2.addItem("Iletin Lente");
            medComboBox2.addItem("ReliOn");

            medComboBox3.addItem("Velosulin BR");
            medComboBox3.addItem("Levemir");
            medComboBox3.addItem("Iletin Lente");
            medComboBox3.addItem("ReliOn");

            medComboBox4.addItem("Velosulin BR");
            medComboBox4.addItem("Levemir");
            medComboBox4.addItem("Iletin Lente");
            medComboBox4.addItem("ReliOn");

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        diseaseLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        medComboBox = new javax.swing.JComboBox();
        quantTextField = new javax.swing.JTextField();
        quant2TextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        medComboBox3 = new javax.swing.JComboBox();
        quant3TextField = new javax.swing.JTextField();
        quant4TextField = new javax.swing.JTextField();
        medComboBox4 = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        notesTextArea = new javax.swing.JTextArea();
        submitBtn = new javax.swing.JButton();
        backBtn1 = new javax.swing.JButton();
        medComboBox2 = new javax.swing.JComboBox();
        nextBtn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        docLabel = new javax.swing.JLabel();
        hospitalName = new javax.swing.JLabel();
        patientLabel = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel1.setText("LIST OF INSULIN MEDICINES");

        diseaseLabel.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        diseaseLabel.setText("<disease>");

        jLabel2.setText("Medication 1:");

        medComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel3.setText("Medication 2:");

        jLabel4.setText("Medication 3:");

        medComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        medComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel5.setText("Medication 4:");

        jLabel7.setText("Additional Notes");

        notesTextArea.setColumns(20);
        notesTextArea.setRows(5);
        jScrollPane1.setViewportView(notesTextArea);

        submitBtn.setText("Prescribe");
        submitBtn.setToolTipText("Give Prescription");
        submitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBtnActionPerformed(evt);
            }
        });

        backBtn1.setIcon(new javax.swing.ImageIcon("/Users/hpanjwani/Documents/NEU/1st Sem/5100 AED Lab/panjwani_hari_001664735/Project/images/back.png")); // NOI18N
        backBtn1.setToolTipText("Go to Previous Page");
        backBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtn1ActionPerformed(evt);
            }
        });

        medComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        nextBtn.setText("Next >>");
        nextBtn.setToolTipText("Go to next Page");
        nextBtn.setEnabled(false);
        nextBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextBtnActionPerformed(evt);
            }
        });

        jLabel6.setText("Medical");

        jLabel8.setText("Quantity");

        docLabel.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        docLabel.setText("<doctorName>");

        hospitalName.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        hospitalName.setText("<hospitalName>");

        patientLabel.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        patientLabel.setText("<patientName>");

        jLabel9.setText("Medical");

        jLabel10.setText("Quantity");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(402, 402, 402)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(docLabel)
                    .addComponent(hospitalName)
                    .addComponent(patientLabel)
                    .addComponent(diseaseLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(medComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(quant2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(66, 66, 66)
                                        .addComponent(jLabel8))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(medComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(quantTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(medComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(quant4TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(66, 66, 66)
                                        .addComponent(jLabel10))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(medComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(quant3TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(nextBtn)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(backBtn1)
                            .addGap(526, 526, 526)
                            .addComponent(submitBtn))))
                .addContainerGap(116, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(324, 324, 324))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(docLabel)
                        .addGap(30, 30, 30)
                        .addComponent(hospitalName)
                        .addGap(30, 30, 30)
                        .addComponent(patientLabel)
                        .addGap(18, 18, 18)
                        .addComponent(diseaseLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(medComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(quant3TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(medComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(quant4TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(medComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(quantTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(quant2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(medComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(25, 25, 25)
                        .addComponent(submitBtn))
                    .addComponent(backBtn1))
                .addGap(18, 18, 18)
                .addComponent(nextBtn)
                .addContainerGap(78, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void submitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBtnActionPerformed
        // TODO add your handling code here:

        appoint = patient.getAppointmentHistory().addAppointment();

        appoint.setDocName(userAccount.getEmployee());
        appoint.setDate(new Date());

        if (quantTextField.getText().trim().isEmpty() && quant2TextField.getText().trim().isEmpty()
                && quant3TextField.getText().trim().isEmpty() && quant4TextField.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "All Dosage cannot be blank! Atleasst one has to be prescribed", "Error", JOptionPane.OK_OPTION);
            quantTextField.setBackground(Color.yellow);
            quant2TextField.setBackground(Color.yellow);
            quant3TextField.setBackground(Color.yellow);
            quant4TextField.setBackground(Color.yellow);

        } else {

            if (!(quantTextField.getText().trim().isEmpty())) {
                if (!(quantTextField.getText().matches("[0-9-]*"))) {
                    patient.getAppointmentHistory().removeAppointment(appoint);
                    JOptionPane.showMessageDialog(this, "Dosage can only have digits!", "Error", JOptionPane.OK_OPTION);
                    quantTextField.setBackground(Color.yellow);
                    return;
                } else {
                    Medicine m = new Medicine();
                    m.setName((String) medComboBox.getSelectedItem());
                    m.setDosage(quantTextField.getText());
                    appoint.getPrescribeMedicineList().add(m);
                }
            }

            if (!(quant2TextField.getText().trim().isEmpty())) {
                if (!(quant2TextField.getText().matches("[0-9-]*"))) {
                    patient.getAppointmentHistory().removeAppointment(appoint);
                    JOptionPane.showMessageDialog(this, "Dosage can only have digits!", "Error", JOptionPane.OK_OPTION);
                    quant2TextField.setBackground(Color.yellow);
                    return;
                } else {
                    Medicine me = new Medicine();
                    me.setName((String) medComboBox2.getSelectedItem());
                    me.setDosage(quant2TextField.getText());
                    appoint.getPrescribeMedicineList().add(me);
                }
            }

            if (!(quant3TextField.getText().trim().isEmpty())) {
                if (!(quant3TextField.getText().matches("[0-9-]*"))) {
                    patient.getAppointmentHistory().removeAppointment(appoint);
                    JOptionPane.showMessageDialog(this, "Dosage can only have digits!", "Error", JOptionPane.OK_OPTION);
                    quant3TextField.setBackground(Color.yellow);
                    return;
                } else {
                    Medicine med = new Medicine();
                    med.setName((String) medComboBox3.getSelectedItem());
                    med.setDosage(quant3TextField.getText());
                    appoint.getPrescribeMedicineList().add(med);
                }
            }

            if (!(quant4TextField.getText().trim().isEmpty())) {
                if (!(quant4TextField.getText().matches("[0-9-]*"))) {
                    patient.getAppointmentHistory().removeAppointment(appoint);
                    JOptionPane.showMessageDialog(this, "Dosage can only have digits!", "Error", JOptionPane.OK_OPTION);
                    quant4TextField.setBackground(Color.yellow);
                    return;
                } else {
                    Medicine mede = new Medicine();
                    mede.setName((String) medComboBox4.getSelectedItem());
                    mede.setDosage(quant4TextField.getText());
                    appoint.getPrescribeMedicineList().add(mede);
                }
            }

            if (diabeteLevel.equals("Type 1")) {
                appoint.setDisease("Diabetes Type I");
            } else if (diabeteLevel.equals("Type 2")) {
                appoint.setDisease("Diabetes Type II");
            }

            appoint.setAdditonalNotes(notesTextArea.getText());

            JOptionPane.showMessageDialog(this, "Details of Appointment saved successfully!!", "INFORMATION", JOptionPane.INFORMATION_MESSAGE);
            
            nextBtn.setEnabled(true);

            if (diabeteLevel.equals("Type 1")) {
                LevelOneDietPlan levelOneDietPlan = new LevelOneDietPlan(userProcessContainer, userAccount, enterprise, patient, diabeteLevel);
                userProcessContainer.add("LevelOneDietPlan", levelOneDietPlan);
                CardLayout layout = (CardLayout) userProcessContainer.getLayout();
                layout.next(userProcessContainer);
            } else if (diabeteLevel.equals("Type 2")) {
                LevelTwoDietPlan levelTwoDietPlan = new LevelTwoDietPlan(userProcessContainer, userAccount, enterprise, patient, diabeteLevel);
                userProcessContainer.add("LevelTwoDietPlan", levelTwoDietPlan);
                CardLayout layout = (CardLayout) userProcessContainer.getLayout();
                layout.next(userProcessContainer);
            }
        }
    }//GEN-LAST:event_submitBtnActionPerformed

    private void backBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtn1ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backBtn1ActionPerformed

    private void nextBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextBtnActionPerformed
        // TODO add your handling code here:
        
        submitBtn.setEnabled(false);
        
        if (diabeteLevel.equals("Type 1")) {
                LevelOneDietPlan levelOneDietPlan = new LevelOneDietPlan(userProcessContainer, userAccount, enterprise, patient, diabeteLevel);
                userProcessContainer.add("LevelOneDietPlan", levelOneDietPlan);
                CardLayout layout = (CardLayout) userProcessContainer.getLayout();
                layout.next(userProcessContainer);
            } else if (diabeteLevel.equals("Type 2")) {
                LevelTwoDietPlan levelTwoDietPlan = new LevelTwoDietPlan(userProcessContainer, userAccount, enterprise,patient, diabeteLevel);
                userProcessContainer.add("LevelTwoDietPlan", levelTwoDietPlan);
                CardLayout layout = (CardLayout) userProcessContainer.getLayout();
                layout.next(userProcessContainer);
            }
    }//GEN-LAST:event_nextBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn1;
    private javax.swing.JLabel diseaseLabel;
    private javax.swing.JLabel docLabel;
    private javax.swing.JLabel hospitalName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox medComboBox;
    private javax.swing.JComboBox medComboBox2;
    private javax.swing.JComboBox medComboBox3;
    private javax.swing.JComboBox medComboBox4;
    private javax.swing.JButton nextBtn;
    private javax.swing.JTextArea notesTextArea;
    private javax.swing.JLabel patientLabel;
    private javax.swing.JTextField quant2TextField;
    private javax.swing.JTextField quant3TextField;
    private javax.swing.JTextField quant4TextField;
    private javax.swing.JTextField quantTextField;
    private javax.swing.JButton submitBtn;
    // End of variables declaration//GEN-END:variables
}
