/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.DiabeteRole;

import Business.Enterprise.Enterprise;
import Business.Patient.Patient;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author hpanjwani
 */
public class MedicationPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private Enterprise enterprise;
    
    private Patient patient;
    private String diabeteLevel;

    /**
     * Creates new form MedicationPanel
     */
    public MedicationPanel(JPanel userProcessContainer, UserAccount userAccount, Enterprise enterprise, Patient patient, String level) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.enterprise = enterprise;
        this.patient = patient;
        this.diabeteLevel = level;

        hospitalName.setText("Hospital Name: "  + enterprise.getName());
        docLabel.setText("Doctor Name: " + userAccount.getUsername());
        dialevel.setText("Diabete Level: Type I");

        if (diabeteLevel.equals("Type 1")) {
            dialevel.setText("Diabete Level: Type I");
        } else {
            dialevel.setText("Diabete Level: Type II");
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        medicationBtnGroup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        oral = new javax.swing.JRadioButton();
        insulin = new javax.swing.JRadioButton();
        backBtn = new javax.swing.JButton();
        nextBtn = new javax.swing.JButton();
        docLabel = new javax.swing.JLabel();
        hospitalName = new javax.swing.JLabel();
        dialevel = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel1.setText("MEDICATION PRESCRIPTION");

        medicationBtnGroup.add(oral);
        oral.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        oral.setText("Do you want to prescribce Oral Medication?");

        medicationBtnGroup.add(insulin);
        insulin.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        insulin.setText("Do you want to prescribe Insulin?");

        backBtn.setIcon(new javax.swing.ImageIcon("/Users/hpanjwani/Documents/NEU/1st Sem/5100 AED Lab/panjwani_hari_001664735/Project/images/back.png")); // NOI18N
        backBtn.setToolTipText("Go to Previous Page");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        nextBtn.setText("Next >>");
        nextBtn.setToolTipText("Go to Next Page");
        nextBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextBtnActionPerformed(evt);
            }
        });

        docLabel.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        docLabel.setText("<doctorName>");

        hospitalName.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        hospitalName.setText("<hospitalName>");

        dialevel.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        dialevel.setText("jLabel18");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(440, 440, 440)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(393, 393, 393)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(docLabel)
                            .addComponent(hospitalName)
                            .addComponent(dialevel)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(435, 435, 435)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(backBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(nextBtn))
                            .addComponent(insulin)
                            .addComponent(oral))))
                .addContainerGap(436, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(docLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(hospitalName)
                .addGap(18, 18, 18)
                .addComponent(dialevel)
                .addGap(65, 65, 65)
                .addComponent(oral)
                .addGap(18, 18, 18)
                .addComponent(insulin)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nextBtn)
                    .addComponent(backBtn))
                .addContainerGap(214, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backBtnActionPerformed

    private void nextBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextBtnActionPerformed
        // TODO add your handling code here:
        if ((oral.isSelected())) {
            OralMedicationPanel oralMedicationPanel = new OralMedicationPanel(userProcessContainer, userAccount, enterprise, patient, diabeteLevel);
            userProcessContainer.add("OralMedicationPanel", oralMedicationPanel);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        } else if (insulin.isSelected()) {
            InsulinMedicationPanel insulinMedicationPanel = new InsulinMedicationPanel(userProcessContainer, userAccount, enterprise, patient, diabeteLevel);
            userProcessContainer.add("InsulinMedicationPanel", insulinMedicationPanel);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        } else {
            JOptionPane.showMessageDialog(this, "Please select atleast one type of medication!", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_nextBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel dialevel;
    private javax.swing.JLabel docLabel;
    private javax.swing.JLabel hospitalName;
    private javax.swing.JRadioButton insulin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.ButtonGroup medicationBtnGroup;
    private javax.swing.JButton nextBtn;
    private javax.swing.JRadioButton oral;
    // End of variables declaration//GEN-END:variables
}
