/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.DiabeteRole;

import Business.Business;
import Business.Enterprise.Enterprise;
import Business.Patient.Patient;
import Business.Patient.VitalSign;
import Business.Patient.VitalSignHistory;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.UserPriviligeWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Component;
import java.sql.Timestamp;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author hpanjwani
 */
public class VitalSignSummary extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private Enterprise enterprise;
    private Business business;
    
    private Patient patient;
    private int age;
    private VitalSignHistory vitalSignHistory;
    private VitalSign vitalSign;
    /**
     * Creates new form VitalSignSummary
     */
    public VitalSignSummary(JPanel userProcessContainer, UserAccount account, Enterprise enterprise, Business business, Patient patient) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.enterprise = enterprise;
        this.business = business;
        
        this.patient = patient;
        
        hospitalName.setText("Hospital Name: "  + enterprise.getName());
        docLabel.setText("Doctor Name: " + userAccount.getUsername());
        patientLabel.setText("Patient Name: " + patient.getName());
        
        age = patient.getAge();
        vitalSignHistory = patient.getVitalSignList();
        
        populateBloodGroup();
    }
    
    public void populateBloodGroup()    {
        bloodGroupComboBox.removeAllItems();
        
        bloodGroupComboBox.addItem("A");
        bloodGroupComboBox.addItem("B");
        bloodGroupComboBox.addItem("AB");
        bloodGroupComboBox.addItem("O");
        bloodGroupComboBox.addItem("B-");
        bloodGroupComboBox.addItem("A-");
        bloodGroupComboBox.addItem("AB-");
        bloodGroupComboBox.addItem("A+");
        bloodGroupComboBox.addItem("B+");
        bloodGroupComboBox.addItem("AB+");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        saveBtn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        timeTextField = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        hemoTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tempTextField = new javax.swing.JTextField();
        glucoseTextField = new javax.swing.JTextField();
        respRate = new javax.swing.JLabel();
        statusLabel = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        Hint = new javax.swing.JButton();
        bpTextField = new javax.swing.JTextField();
        plateletsTextField = new javax.swing.JTextField();
        weight = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        respRateTextField = new javax.swing.JTextField();
        pulseTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        heartRateTextField = new javax.swing.JTextField();
        bp = new javax.swing.JLabel();
        weightTextField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        heartRate = new javax.swing.JLabel();
        bloodGroupComboBox = new javax.swing.JComboBox();
        docLabel = new javax.swing.JLabel();
        hospitalName = new javax.swing.JLabel();
        patientLabel = new javax.swing.JLabel();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel1.setText("VITAL SIGN SUMMARY");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, -1, -1));

        saveBtn.setText("Save");
        saveBtn.setToolTipText("Record Vital Sign");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });
        jPanel1.add(saveBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 394, -1, -1));

        jLabel6.setText("Time of detail entered:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(443, 453, -1, -1));

        timeTextField.setText("time");
        jPanel1.add(timeTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 449, 170, 24));

        jButton1.setText("Medical History");
        jButton1.setToolTipText("Patient Medical History");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(829, 99, -1, -1));

        jButton2.setIcon(new javax.swing.ImageIcon("/Users/hpanjwani/Documents/NEU/1st Sem/5100 AED Lab/panjwani_hari_001664735/Project/images/back.png")); // NOI18N
        jButton2.setToolTipText("Go to Previous Page");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 394, -1, -1));
        jPanel1.add(hemoTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(443, 228, 100, -1));

        jLabel5.setText("Weight (in pounds):");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 317, -1, -1));
        jPanel1.add(tempTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(757, 350, 100, -1));
        jPanel1.add(glucoseTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(443, 183, 100, -1));
        jPanel1.add(respRate, new org.netbeans.lib.awtextra.AbsoluteConstraints(909, 191, 83, 18));
        jPanel1.add(statusLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(909, 140, 83, 25));

        jLabel17.setText("Body Temperature");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 355, -1, -1));

        jLabel16.setText("Pulse");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 317, -1, -1));

        jLabel15.setText("Blood Group");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 271, -1, -1));

        Hint.setText("Hint");
        Hint.setToolTipText("Normal Range");
        Hint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HintActionPerformed(evt);
            }
        });
        jPanel1.add(Hint, new org.netbeans.lib.awtextra.AbsoluteConstraints(909, 394, -1, -1));
        jPanel1.add(bpTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(757, 266, 99, -1));
        jPanel1.add(plateletsTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(439, 350, 99, -1));
        jPanel1.add(weight, new org.netbeans.lib.awtextra.AbsoluteConstraints(909, 320, 83, 18));

        jLabel2.setText("Respiration Rate:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(591, 188, -1, -1));

        jLabel14.setText("Blood Platelets");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 355, -1, -1));

        jLabel13.setText("Hemoglobin Level");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 233, -1, -1));

        respRateTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                respRateTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(respRateTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(757, 183, 100, -1));
        jPanel1.add(pulseTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(439, 312, 100, -1));

        jLabel3.setText("Heart Rate:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(591, 233, -1, -1));
        jPanel1.add(heartRateTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(757, 228, 100, -1));
        jPanel1.add(bp, new org.netbeans.lib.awtextra.AbsoluteConstraints(909, 266, 83, 19));
        jPanel1.add(weightTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(757, 312, 100, -1));

        jLabel12.setText("Blood Glucose Level");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 186, -1, 20));

        jLabel4.setText("Systolic Blood Pressure:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 271, -1, -1));
        jPanel1.add(heartRate, new org.netbeans.lib.awtextra.AbsoluteConstraints(909, 236, 83, 18));

        bloodGroupComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(bloodGroupComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(443, 267, -1, -1));

        docLabel.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        docLabel.setText("<doctorName>");
        jPanel1.add(docLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(327, 63, -1, -1));

        hospitalName.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        hospitalName.setText("<hospitalName>");
        jPanel1.add(hospitalName, new org.netbeans.lib.awtextra.AbsoluteConstraints(327, 103, -1, -1));

        patientLabel.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        patientLabel.setText("<patientName>");
        jPanel1.add(patientLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(327, 143, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        // TODO add your handling code here:

        Timestamp timeStamp = new Timestamp(new Date().getTime());
        String time = String.valueOf(timeStamp);
        timeTextField.setText(String.valueOf(time));

        if (age == 0) {
            JOptionPane.showMessageDialog(this, "Please Enter Patient details!!", "Error", JOptionPane.OK_OPTION);
            resetFields();
        } else {
            if (respRateTextField.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Respiration Rate cannot be blank!", "Error", JOptionPane.OK_OPTION);
                respRateTextField.setBackground(Color.red);
            } else if (!respRateTextField.getText().matches("^(\\d+\\.)?\\d+$")) {
                JOptionPane.showMessageDialog(this, "Respiration Rate can only have digits!", "Error", JOptionPane.OK_OPTION);
                respRateTextField.setBackground(Color.red);
            } else if (heartRateTextField.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Heart Rate cannot be blank!", "Error", JOptionPane.OK_OPTION);
                heartRateTextField.setBackground(Color.red);
            } else if (!heartRateTextField.getText().matches("^(\\d+\\.)?\\d+$")) {
                JOptionPane.showMessageDialog(this, "Heart Rate can only have digits!", "Error", JOptionPane.OK_OPTION);
                heartRateTextField.setBackground(Color.red);
            } else if (bpTextField.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Blood Pressure cannot be blank!", "Error", JOptionPane.OK_OPTION);
                bpTextField.setBackground(Color.red);
            } else if (!bpTextField.getText().matches("^(\\d+\\.)?\\d+$")) {
                JOptionPane.showMessageDialog(this, "Blood Pressure can only have digits!", "Error", JOptionPane.OK_OPTION);
                bpTextField.setBackground(Color.red);
            } else if (weightTextField.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Weight cannot be blank!", "Error", JOptionPane.OK_OPTION);
                weightTextField.setBackground(Color.red);
            } else if (!weightTextField.getText().matches("^(\\d+\\.)?\\d+$")) {
                JOptionPane.showMessageDialog(this, "Weight can only have digits!", "Error", JOptionPane.OK_OPTION);
                weightTextField.setBackground(Color.red);
            } else {

                vitalSign = vitalSignHistory.addVitalSign();

                vitalSign.setRespRate(Float.parseFloat(respRateTextField.getText()));
                vitalSign.setHeartRate(Float.parseFloat(heartRateTextField.getText()));
                vitalSign.setBp(Float.parseFloat(bpTextField.getText()));
                vitalSign.setWeight(Float.parseFloat(weightTextField.getText()));
                vitalSign.setGlucose(Float.parseFloat(glucoseTextField.getText()));
                vitalSign.setHemo(Float.parseFloat(hemoTextField.getText()));
                vitalSign.setBloodGroup((String)bloodGroupComboBox.getSelectedItem());
                vitalSign.setPulse(Integer.parseInt(pulseTextField.getText()));
                vitalSign.setPlatelets(Float.parseFloat(plateletsTextField.getText()));
                vitalSign.setTemp(Float.parseFloat(tempTextField.getText()));
                vitalSign.setTime(time);

                JOptionPane.showMessageDialog(this, "VitalSign Record is successfully saved!", "Information", JOptionPane.INFORMATION_MESSAGE);
                resetFields();

                DiabeteSymptoms diabeteSymptoms = new DiabeteSymptoms(userProcessContainer, userAccount, enterprise, patient);
                userProcessContainer.add("DiabeteSymptoms", diabeteSymptoms);
                CardLayout layout = (CardLayout) userProcessContainer.getLayout();
                layout.next(userProcessContainer);
            }
        }
        }

        public void resetFields() {
            respRateTextField.setText("");
            respRateTextField.setBackground(Color.white);
            heartRateTextField.setText("");
            heartRateTextField.setBackground(Color.white);
            bpTextField.setText("");
            bpTextField.setBackground(Color.white);
            weightTextField.setText("");
            weightTextField.setBackground(Color.white);
            //timeTextField.setText(String.valueOf(vs.getTime()));
    }//GEN-LAST:event_saveBtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        MedicalHistory patientMedicalHistory = new MedicalHistory(userProcessContainer, userAccount, enterprise, patient);
        userProcessContainer.add("PatientMedicalHistoryPanel", patientMedicalHistory);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        CheckUpPanel waitingPanel = (CheckUpPanel) component;
        waitingPanel.populatePatientCombo();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void HintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HintActionPerformed
        // TODO add your handling code here:

        statusLabel.setText("Normal Status");

        if ((age >= 1) && (age <= 3)) {
            respRate.setText("20-30");
            heartRate.setText("80-130");
            weight.setText("80-110");
            bp.setText("22-31");
        } else if ((age >= 4) && (age <= 5)) {
            respRate.setText("20-30");
            heartRate.setText("80-120");
            weight.setText("80-110");
            bp.setText("31-40");
        } else if ((age >= 6) && (age <= 12)) {
            respRate.setText("20-30");
            heartRate.setText("70-110");
            weight.setText("80-120");
            bp.setText("41-92");
        } else {
            respRate.setText("12-20");
            heartRate.setText("55-105");
            weight.setText("110-120");
            bp.setText("> 110");
        }
    }//GEN-LAST:event_HintActionPerformed

    private void respRateTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_respRateTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_respRateTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Hint;
    private javax.swing.JComboBox bloodGroupComboBox;
    private javax.swing.JLabel bp;
    private javax.swing.JTextField bpTextField;
    private javax.swing.JLabel docLabel;
    private javax.swing.JTextField glucoseTextField;
    private javax.swing.JLabel heartRate;
    private javax.swing.JTextField heartRateTextField;
    private javax.swing.JTextField hemoTextField;
    private javax.swing.JLabel hospitalName;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel patientLabel;
    private javax.swing.JTextField plateletsTextField;
    private javax.swing.JTextField pulseTextField;
    private javax.swing.JLabel respRate;
    private javax.swing.JTextField respRateTextField;
    private javax.swing.JButton saveBtn;
    private javax.swing.JLabel statusLabel;
    private javax.swing.JTextField tempTextField;
    private javax.swing.JLabel timeTextField;
    private javax.swing.JLabel weight;
    private javax.swing.JTextField weightTextField;
    // End of variables declaration//GEN-END:variables
}
