/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.PatientRole;

import Business.Enterprise.Enterprise;
import Business.Organization.Hospital.LabOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.UserPriviligeWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hpanjwani
 */
public class LabHistoryPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private Enterprise enterprise;
    
    /**
     * Creates new form LabHistoryPanel
     */
    public LabHistoryPanel(JPanel userProcessContainer, UserAccount userAccount, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.enterprise = enterprise;
        
        patientLabel.setText("Patient Name: " + userAccount.getUsername());
        enterpriseLabel.setText("Hospital Name: " + enterprise.getName());
        
        populateLabTestTable();
    }

    public void populateLabTestTable() {

        DefaultTableModel model = (DefaultTableModel) labTestTable.getModel();
        model.setRowCount(0);

        for (WorkRequest request : userAccount.getWorkQueue().getWorkRequestList()) {
            if ((request.getStatus().equals("Pending Test")) || (request.getStatus().equals("Processing Test"))
                    || (request.getStatus().equals("Test Completed"))) {
//
//                Patient patient = (Patient) ((UserPriviligeWorkRequest) request).getPatient();

                //int size = patient.getDonationList().size() - 1;
//                if(size < 0)   {
//                    break;
//                }
//                else    {
                Object[] row = new Object[8];

                row[0] = request;
                row[1] = request.getSender();
                row[2] = request.getReceiver();
                row[3] = ((UserPriviligeWorkRequest) request).getPatient();
                row[4] = request.getRequestDate();
                row[5] = request.getResolveDate();
                String result = ((UserPriviligeWorkRequest) request).getTestResult() == null ? null : ((UserPriviligeWorkRequest) request).getTestResult();
                row[6] = result;
                row[7] = request.getStatus();
//                    row[5] = request.getResolveDate();
//                    String result = ((LabTestWorkRequest) request).getTestResult();
//                    row[6] = result == null ? "Waiting" : result;
//                    
//                    if(result != null)    {
//                        for(int j = 0; j < d.getDonationList().size(); j++)   {
//                            if(d.getDonationList().get(j).equals(result))   {
//                                size  = j;
//                                System.out.println(size);
//                                break;
//                            }
//                        }
//                    }
//                    
//                    int unit = d.getDonationList().get(size).getUnit();
//                    row[7] = String.valueOf(unit) == null ? "Waiting" : String.valueOf(unit);

                model.addRow(row);
                //}
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        labTestTable = new javax.swing.JTable();
        backBtn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        patientLabel = new javax.swing.JLabel();
        enterpriseLabel = new javax.swing.JLabel();

        labTestTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Test Name", "Doctor Name", "Lab Assistant", "Patient Name", "Request Date", "Resolve Date", "Result", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        labTestTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                labTestTableMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(labTestTable);

        backBtn.setText("<< Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel7.setText("LAB REPORTS");

        patientLabel.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        patientLabel.setText("jLabel2");

        enterpriseLabel.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        enterpriseLabel.setText("jLabel3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(337, 337, 337)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(enterpriseLabel)
                    .addComponent(patientLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(279, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(backBtn)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 760, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(198, 198, 198))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(517, 517, 517))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel7)
                .addGap(30, 30, 30)
                .addComponent(patientLabel)
                .addGap(24, 24, 24)
                .addComponent(enterpriseLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(backBtn)
                .addGap(128, 128, 128))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void labTestTableMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labTestTableMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_labTestTableMousePressed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable labTestTable;
    private javax.swing.JLabel patientLabel;
    // End of variables declaration//GEN-END:variables
}
