/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.AdminstrativeRole;

import Business.Customer;
import Business.Order;
import Business.OrderCatalog;
import Business.OrderItem;
import Business.Product;
import Business.SalePerson;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JPanel;

/**
 *
 * @author hpanjwani
 */
public class BestProductPanel extends javax.swing.JPanel {
    
    private JPanel userProcessContainer;
    private OrderCatalog orderCatalog;
    private ArrayList<OrderItem> tempItemList;
    private OrderItem bestItem;
    
    private int flag =0;
  
    /**
     * Creates new form BestProductPanel
     */
    public BestProductPanel(JPanel upc, OrderCatalog orderCatalog) {
        initComponents();
        userProcessContainer = upc;
        this.orderCatalog = orderCatalog;
        
        bestItem = new OrderItem();
        
        tempItemList = new ArrayList<>(); 
        
        bestProduct();
    }
    
    public void bestProduct()  {
        
        for(Order order : orderCatalog.getOrderCatalog())   {
            for(OrderItem item : order.getOrderItemList())  {
                if(tempItemList.isEmpty())
                    tempItemList.add(item);

                else    {
                    for(int i = 0; i < tempItemList.size(); i++)    {
                        if(item.getProduct().getProdName().equals(tempItemList.get(i).getProduct().getProdName()))  {
                            tempItemList.get(i).setVolume(item.getVolume() + tempItemList.get(i).getVolume());
                            flag = 1;
                            break;
                        }
                    }     
                    if(flag == 0)   {
                        tempItemList.add(item);  
                    }
                        flag = 0;
                    }
                }                    
            }
        
        
        for(int i = 0; i < (tempItemList.size()); i++)    {
            
            if( i == 0 )    {
                bestItem = tempItemList.get(i);
            } else if(bestItem.getVolume() < tempItemList.get(i).getVolume())
                bestItem = tempItemList.get(i);
        }
        
        nameTextField.setText(bestItem.getProduct().getProdName());
        volumeTextField.setText(String.valueOf(bestItem.getVolume()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nameTextField = new javax.swing.JLabel();
        volumeTextField = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("TOP PRODUCT BY VOLUME");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("PRODUCT NAME:");

        nameTextField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nameTextField.setText("jLabel2");

        volumeTextField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        volumeTextField.setText("jLabel2");

        jButton1.setText("<< Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("SALE VOLUME:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(volumeTextField))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(nameTextField)))))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nameTextField))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(volumeTextField)
                    .addComponent(jLabel3))
                .addGap(50, 50, 50)
                .addComponent(jButton1)
                .addContainerGap(89, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel nameTextField;
    private javax.swing.JLabel volumeTextField;
    // End of variables declaration//GEN-END:variables
}
