/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.AdminstrativeRole;

import Business.CustomerDirectory;
import Business.OrderCatalog;
import Business.SalePersonDirectory;
import Business.SupplierDirectory;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author hpanjwani
 */
public class ReportPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private SalePersonDirectory salePersonDirectory;
    private CustomerDirectory customerDirectory;
    private OrderCatalog orderCatalog;
    
    /**
     * Creates new form ReportPanel
     */
    public ReportPanel(JPanel upc, SalePersonDirectory salePersonDirectory, CustomerDirectory customerDirectory, OrderCatalog orderCatalog) {
        initComponents();
        userProcessContainer = upc;
        this.salePersonDirectory = salePersonDirectory;
        this.customerDirectory = customerDirectory;
        this.orderCatalog = orderCatalog;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        topSalePersonBtn = new javax.swing.JButton();
        popularProductBtn = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        customerBtn = new javax.swing.JButton();

        topSalePersonBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        topSalePersonBtn.setText("Best Sale Person >>");
        topSalePersonBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                topSalePersonBtnActionPerformed(evt);
            }
        });

        popularProductBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        popularProductBtn.setText("Best PRODUCT  >>");
        popularProductBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popularProductBtnActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton2.setText("Review SalePerson Performance >>");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("REPORT GENERATION");

        btnBack.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        customerBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        customerBtn.setText("Best CUSTOMER  >>");
        customerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(33, 33, 33)
                            .addComponent(jLabel1))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButton2)
                                .addComponent(topSalePersonBtn)
                                .addComponent(popularProductBtn)
                                .addComponent(customerBtn))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(150, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(topSalePersonBtn)
                .addGap(18, 18, 18)
                .addComponent(popularProductBtn)
                .addGap(18, 18, 18)
                .addComponent(customerBtn)
                .addGap(18, 18, 18)
                .addComponent(btnBack)
                .addContainerGap(25, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void topSalePersonBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_topSalePersonBtnActionPerformed

        BestSalePersonPanel bsp = new BestSalePersonPanel(userProcessContainer, salePersonDirectory);
        userProcessContainer.add("BestSalePersonJPanel", bsp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_topSalePersonBtnActionPerformed

    private void popularProductBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popularProductBtnActionPerformed
        
        BestProductPanel bp = new BestProductPanel(userProcessContainer, orderCatalog);
        userProcessContainer.add("BestProductPanel", bp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_popularProductBtnActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        SalePersonPerformancePanel sppp = new SalePersonPerformancePanel(userProcessContainer, salePersonDirectory);
        userProcessContainer.add("SalePersonPerformancePanel", sppp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void customerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerBtnActionPerformed
        // TODO add your handling code here:
        
        CustomerReviewPanel crp = new CustomerReviewPanel(userProcessContainer, customerDirectory);
        userProcessContainer.add("CustomerReviewPanel", crp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_customerBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton customerBtn;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton popularProductBtn;
    private javax.swing.JButton topSalePersonBtn;
    // End of variables declaration//GEN-END:variables
}
