/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.Patient;
import Business.Person;
import Business.VitalSign;
import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.renderer.category.BarRenderer;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author hpanjwani
 */
public class SearchResultPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Person person;
    private Patient patient;
    private int age;
    private DefaultCategoryDataset vitalSignDataSet;
    private VitalSign vs;
    /**
     * Creates new form SearchResultPanel
     */
    public SearchResultPanel(Person person, JPanel userProcessContainer) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.person = person;
        
        patient = person.getPatientList().get(0);
        
        age = patient.getAge();
        
        name.setText(person.getFirstName());
        
        pIDTextField.setText(String.valueOf(patient.getpID()));
        nameTextField.setText(patient.getpName());
        ageTextField.setText(String.valueOf(patient.getAge()));
        docNameTextField.setText(patient.getDocName());
        pharmacyTextField.setText(patient.getPharmacy());
        
        populateTable();   
    }
    
    public void populateTable() {
        //Get the Table Model
        DefaultTableModel dtm = (DefaultTableModel)vitalSignTable.getModel();
        
        dtm.setRowCount(0);
        
        for(VitalSign vs :  patient.getVitalSignHistory().getVitalSignList())   {   
            Object row[] = new Object[6];
            
            row[0] = vs.getRespRate();
            row[1] = vs.getHeartRate();
            row[2] = vs.getBp();
            row[3] = vs.getWeight();
            row[4] = vs;
            
            if(age >= 1 && age <= 3)   {
                if( ((vs.getRespRate() < 20) || (vs.getRespRate() > 30)) ||
                     (vs.getHeartRate() < 80) || (vs.getHeartRate() > 130) ||
                     (vs.getBp() < 80) || (vs.getBp() > 110) ||
                     (vs.getWeight() < 22) || (vs.getWeight() > 31))  
                {
                    row[5] = "Abnormal";
                }
                else    {
                    row[5] = "Normal";
                }
            }
            else if(age >= 4 && age <= 5)   {
                if( ((vs.getRespRate() < 20) || (vs.getRespRate() > 30)) ||
                     (vs.getHeartRate() < 80) || (vs.getHeartRate() > 120) ||
                     (vs.getBp() < 80) || (vs.getBp() >= 110) ||
                     (vs.getWeight() < 31) || (vs.getWeight() > 40))  
                {
                    row[5] = "Abormal";
                }
                else    {
                    row[5] = "Normal";
                }
            }
            else if(age >= 6 && age <= 12)   {
                if( ((vs.getRespRate() < 20) || (vs.getRespRate() > 30)) ||
                     (vs.getHeartRate() < 70) || (vs.getHeartRate() > 110) ||
                     (vs.getBp() < 80) || (vs.getBp() >= 120) ||
                     (vs.getWeight() < 41) || (vs.getWeight() >= 92))  
                {
                    row[5] = "Abnormal";
                }
                else    {
                    row[5] = "Normal";
                }
            }
            else {
                if( ((vs.getRespRate() < 12) || (vs.getRespRate() > 20)) ||
                     (vs.getHeartRate() < 55) || (vs.getHeartRate() > 105) ||
                     (vs.getBp() < 110) || (vs.getBp() >= 120) ||
                     (vs.getWeight() < 110))
                {
                    row[5] = "Abnormal";
                }
                else    {
                    row[5] = "Normal";
                }
            }
       
            //add each person to the table for dispalay
            dtm.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        pIDTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        ageTextField = new javax.swing.JTextField();
        pharmacyTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        docNameTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        vitalSignTable = new javax.swing.JTable();
        backBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        respRate = new javax.swing.JLabel();
        heartRate = new javax.swing.JLabel();
        bp = new javax.swing.JLabel();
        weight = new javax.swing.JLabel();
        Hint = new javax.swing.JButton();
        status = new javax.swing.JLabel();
        graphBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 255));

        jLabel3.setBackground(new java.awt.Color(255, 255, 204));
        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel3.setText("Patient ID:");

        pIDTextField.setEditable(false);

        jLabel2.setBackground(new java.awt.Color(255, 255, 204));
        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel2.setText("Patient Name:");

        nameTextField.setEditable(false);
        nameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTextFieldActionPerformed(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(255, 255, 204));
        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel4.setText("Age:");

        ageTextField.setEditable(false);

        pharmacyTextField.setEditable(false);

        jLabel6.setBackground(new java.awt.Color(255, 255, 204));
        jLabel6.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel6.setText("Preffered Pharmacy:");

        docNameTextField.setEditable(false);

        jLabel5.setBackground(new java.awt.Color(255, 255, 204));
        jLabel5.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel5.setText("Primary Doctor Name:");

        vitalSignTable.setBackground(new java.awt.Color(204, 255, 255));
        vitalSignTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "RespRate", "HeartRate", "Blood Pressure", "Weight", "Timestamp", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(vitalSignTable);
        if (vitalSignTable.getColumnModel().getColumnCount() > 0) {
            vitalSignTable.getColumnModel().getColumn(0).setResizable(false);
            vitalSignTable.getColumnModel().getColumn(1).setResizable(false);
            vitalSignTable.getColumnModel().getColumn(2).setResizable(false);
            vitalSignTable.getColumnModel().getColumn(3).setResizable(false);
            vitalSignTable.getColumnModel().getColumn(4).setResizable(false);
            vitalSignTable.getColumnModel().getColumn(5).setResizable(false);
        }

        backBtn.setBackground(new java.awt.Color(255, 255, 204));
        backBtn.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        backBtn.setText("<< Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setText("SEARCH RESULT FOR PATIENT# ");

        name.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        name.setText("jLabel7");

        respRate.setBackground(new java.awt.Color(255, 255, 204));
        respRate.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N

        heartRate.setBackground(new java.awt.Color(255, 255, 204));
        heartRate.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N

        bp.setBackground(new java.awt.Color(255, 255, 204));
        bp.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N

        weight.setBackground(new java.awt.Color(255, 255, 204));
        weight.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N

        Hint.setBackground(new java.awt.Color(255, 255, 204));
        Hint.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        Hint.setText("Hint");
        Hint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HintActionPerformed(evt);
            }
        });

        status.setBackground(new java.awt.Color(255, 255, 204));
        status.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N

        graphBtn.setBackground(new java.awt.Color(255, 255, 204));
        graphBtn.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        graphBtn.setText("View Graphical Representation");
        graphBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                graphBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(201, 201, 201)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(name))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addGap(18, 18, 18)
                                    .addComponent(docNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel6)
                                    .addGap(18, 18, 18)
                                    .addComponent(pharmacyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(18, 18, 18)
                                    .addComponent(pIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel2)
                                    .addGap(18, 18, 18)
                                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel4)
                                    .addGap(18, 18, 18)
                                    .addComponent(ageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 578, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(backBtn)
                                .addGap(247, 247, 247)
                                .addComponent(graphBtn)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Hint)
                            .addComponent(status, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bp, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(respRate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(heartRate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(weight, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(name))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(ageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(docNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(pharmacyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(backBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(208, 208, 208)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Hint)
                            .addComponent(graphBtn)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(status, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(heartRate, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bp, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(weight, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(respRate, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(86, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTextFieldActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backBtnActionPerformed

    private void HintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HintActionPerformed
        // TODO add your handling code here:

        status.setText("Normal Status");

        if((age >= 1) && (age <= 3)) {
            respRate.setText("20-30");
            heartRate.setText("80-130");
            bp.setText("80-110");
            weight.setText("22-31");
        }
        else if((age >= 4) && (age <= 5)) {
            respRate.setText("20-30");
            heartRate.setText("80-120");
            bp.setText("80-110");
            weight.setText("31-40");
        }
        else if((age >= 6) && (age <= 12)) {
            respRate.setText("20-30");
            heartRate.setText("70-110");
            bp.setText("80-120");
            weight.setText("41-92");
        }
        else  {
            respRate.setText("12-20");
            heartRate.setText("55-105");
            bp.setText("110-120");
            weight.setText("> 110");
        }
    }//GEN-LAST:event_HintActionPerformed
    
    public void populateGraph() {
      try   {
        vitalSignDataSet = new DefaultCategoryDataset();
          
        for(VitalSign vs : patient.getVitalSignHistory().getVitalSignList())   {
            
            vitalSignDataSet.addValue(vs.getRespRate(), "Respiration Rate", vs.getTime());
            vitalSignDataSet.addValue(vs.getHeartRate(), "Heart Rate", vs.getTime());
            vitalSignDataSet.addValue(vs.getBp(), "Blood Pressure", vs.getTime());
            vitalSignDataSet.addValue(vs.getWeight(), "Weight", vs.getTime());
        }
        
        JFreeChart chartFactory = ChartFactory.createBarChart3D("VitalSign Pattern", "Timestamp", "VitalSign", vitalSignDataSet, PlotOrientation.VERTICAL, true, true, false);      
        BarRenderer renderer = null;
        CategoryPlot plot = chartFactory.getCategoryPlot();
        plot.setRangeGridlinePaint(Color.BLUE);
        renderer = new BarRenderer();
        
        ChartFrame frame = new ChartFrame("Bar Chart for VitalSign", chartFactory);
        frame.setVisible(true);
        frame.setSize(700, 700);
        
//        ChartPanel panel = new ChartPanel(chartFactory);
//        
//        this.removeAll();
//        this.add(panel);
//        this.updateUI();
        
        int length = (patient.getVitalSignHistory().getVitalSignList().size() - 1) ;
        
        vs = patient.getVitalSignHistory().getVitalSignList().get(length);
        
        if(age >= 1 && age <= 3)   {
                if( ((vs.getRespRate() < 20) || (vs.getRespRate() > 30)) ||
                     (vs.getHeartRate() < 80) || (vs.getHeartRate() > 130) ||
                     (vs.getBp() < 80) || (vs.getBp() > 110) ||
                     (vs.getWeight() < 22) || (vs.getWeight() > 31))  
                {
                    JOptionPane.showMessageDialog(this, "The last vital sign of the Patient is Abnormal!\n Please take a good look on the graph", "INFORMATION", JOptionPane.INFORMATION_MESSAGE);
                }
//                else    {
//                    row[5] = "Normal";
//                }
            }
            else if(age >= 4 && age <= 5)   {
                if( ((vs.getRespRate() < 20) || (vs.getRespRate() > 30)) ||
                     (vs.getHeartRate() < 80) || (vs.getHeartRate() > 120) ||
                     (vs.getBp() < 80) || (vs.getBp() >= 110) ||
                     (vs.getWeight() < 31) || (vs.getWeight() > 40))  
                {
                    JOptionPane.showMessageDialog(this, "The last vital sign of the Patient is Abnormal!\n Please take a good look on the graph", "INFORMATION", JOptionPane.INFORMATION_MESSAGE);
                }
//                else    {
//                    row[5] = "Normal";
//                }
            }
            else if(age >= 6 && age <= 12)   {
                if( ((vs.getRespRate() < 20) || (vs.getRespRate() > 30)) ||
                     (vs.getHeartRate() < 70) || (vs.getHeartRate() > 110) ||
                     (vs.getBp() < 80) || (vs.getBp() >= 120) ||
                     (vs.getWeight() < 41) || (vs.getWeight() >= 92))  
                {
                    JOptionPane.showMessageDialog(this, "The last vital sign of the Patient is Abnormal!\n Please take a good look on the graph", "INFORMATION", JOptionPane.INFORMATION_MESSAGE);
                }
//                else    {
//                    row[5] = "Normal";
//                }
            }
            else {
                if( ((vs.getRespRate() < 12) || (vs.getRespRate() > 20)) ||
                     (vs.getHeartRate() < 55) || (vs.getHeartRate() > 105) ||
                     (vs.getBp() < 110) || (vs.getBp() >= 120) ||
                     (vs.getWeight() > 110))
                {
                    JOptionPane.showMessageDialog(this, "The last vital sign of the Patient is Abnormal!\n Please take a good look on the graph", "INFORMATION", JOptionPane.INFORMATION_MESSAGE);
                }
//                else    {
//                    row[5] = "Normal";
//                }
            }
      }
      catch(Exception e)    {
          System.out.println(e);
      }   
    }
    
    private void graphBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_graphBtnActionPerformed
        // TODO add your handling code here:
        
        populateGraph();
        
//        GraphPanel graphPanel = new GraphPanel(person, userProcessContainer);
//        userProcessContainer.add("GraphPanel", graphPanel);
//        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
//        layout.next(userProcessContainer);
    }//GEN-LAST:event_graphBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Hint;
    private javax.swing.JTextField ageTextField;
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel bp;
    private javax.swing.JTextField docNameTextField;
    private javax.swing.JButton graphBtn;
    private javax.swing.JLabel heartRate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel name;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JTextField pIDTextField;
    private javax.swing.JTextField pharmacyTextField;
    private javax.swing.JLabel respRate;
    private javax.swing.JLabel status;
    private javax.swing.JTable vitalSignTable;
    private javax.swing.JLabel weight;
    // End of variables declaration//GEN-END:variables
}
