/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ReceptionistRole;

import Business.Business;
import Business.Enterprise.Enterprise;
import Business.Organization.Hospital.Organization;
import Business.Organization.Hospital.PatientOrganization;
import Business.Organization.Hospital.ReceptionistOrganization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author hpanjwani
 */
public class ReceptionistWorkAreaPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private ReceptionistOrganization receptionistOrganization;
    private PatientOrganization patientOrganization;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private Business business;

    /**
     * Creates new form ReceptionistWorkAreaPanel
     */
    public ReceptionistWorkAreaPanel(JPanel userProcessContainer, UserAccount userAccount, ReceptionistOrganization organization, Enterprise enterprise, Business business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.receptionistOrganization = organization;
        this.enterprise = enterprise;
        this.userAccount = userAccount;
        this.business = business;

        for (Organization org : enterprise.getOrganizationDirectory().getOrganizationList()) {
            if (org instanceof PatientOrganization) {
                patientOrganization = (PatientOrganization) org;
            } else if (org instanceof ReceptionistOrganization) {
                receptionistOrganization = (ReceptionistOrganization) org;
            }
        }
        recLabel.setText(("Receptionist Name: " + userAccount.getUsername()));
        hospitalLabel.setText("Hospital Name: " + enterprise.getName() );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        requestAppointmentBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        notificationBtn = new javax.swing.JButton();
        registerBtn = new javax.swing.JButton();
        recLabel = new javax.swing.JLabel();
        hospitalLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        requestAppointmentBtn.setIcon(new javax.swing.ImageIcon("/Users/hpanjwani/Documents/NEU/1st Sem/5100 AED Lab/panjwani_hari_001664735/Project/images/opt.jpg")); // NOI18N
        requestAppointmentBtn.setToolTipText("OPT Ticket");
        requestAppointmentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestAppointmentBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon("/Users/hpanjwani/Documents/NEU/1st Sem/5100 AED Lab/panjwani_hari_001664735/Project/images/Reception.jpg")); // NOI18N
        jLabel1.setText("\n\n");
        jLabel1.setToolTipText("Receptionist Dashboard");

        notificationBtn.setIcon(new javax.swing.ImageIcon("/Users/hpanjwani/Documents/NEU/1st Sem/5100 AED Lab/panjwani_hari_001664735/Project/images/ambulance.jpg")); // NOI18N
        notificationBtn.setToolTipText("Ambulance Request");
        notificationBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notificationBtnActionPerformed(evt);
            }
        });

        registerBtn.setIcon(new javax.swing.ImageIcon("/Users/hpanjwani/Documents/NEU/1st Sem/5100 AED Lab/panjwani_hari_001664735/Project/images/registeration.jpeg")); // NOI18N
        registerBtn.setToolTipText("Patient Registeration");
        registerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerBtnActionPerformed(evt);
            }
        });

        recLabel.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        recLabel.setText("jLabel2");

        hospitalLabel.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        hospitalLabel.setText("jLabel2");

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel2.setText("RECEPTIONIST DASHBOARD");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(258, 258, 258)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hospitalLabel)
                            .addComponent(recLabel)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(registerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(133, 133, 133)
                                .addComponent(requestAppointmentBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(135, 135, 135)
                                .addComponent(notificationBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(430, 430, 430)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(recLabel)
                .addGap(18, 18, 18)
                .addComponent(hospitalLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(requestAppointmentBtn)
                    .addComponent(registerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(notificationBtn))
                .addContainerGap(73, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void requestAppointmentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestAppointmentBtnActionPerformed
        // TODO add your handling code here:
        SelectPatientPanel selectPatientPanel = new SelectPatientPanel(userProcessContainer, userAccount, receptionistOrganization, enterprise, business);
        userProcessContainer.add("SelectPatientPanel", selectPatientPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_requestAppointmentBtnActionPerformed

    private void notificationBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notificationBtnActionPerformed
        // TODO add your handling code here:
        RequestAmbulancePanel requestAmbulancePanel = new RequestAmbulancePanel(userProcessContainer, userAccount, receptionistOrganization, enterprise);
        userProcessContainer.add("RequestAmbulancePanel", requestAmbulancePanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_notificationBtnActionPerformed

    private void registerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerBtnActionPerformed
        // TODO add your handling code here:
        CreatePatientPanel createPatientPanel = new CreatePatientPanel(userProcessContainer, userAccount, patientOrganization, enterprise, business);
        userProcessContainer.add("CreatePatientPanel", createPatientPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_registerBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel hospitalLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton notificationBtn;
    private javax.swing.JLabel recLabel;
    private javax.swing.JButton registerBtn;
    private javax.swing.JButton requestAppointmentBtn;
    // End of variables declaration//GEN-END:variables
}
