/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ReceptionistRole;

import Business.Business;
import Business.Enterprise.Enterprise;
import Business.Organization.Hospital.Organization;
import Business.Organization.Hospital.PatientOrganization;
import Business.Organization.Hospital.ReceptionistOrganization;
import Business.Patient.Patient;
import Business.Person.Person;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author hpanjwani
 */
public class SelectPatientPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private ReceptionistOrganization receptionistOrganization;
    private PatientOrganization patientOrganization;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private Business business;
    
    /**
     * Creates new form SelectPatient
     */
    public SelectPatientPanel(JPanel userProcessContainer, UserAccount userAccount, ReceptionistOrganization organization, Enterprise enterprise, Business business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.receptionistOrganization = organization;
        this.enterprise = enterprise;
        this.userAccount = userAccount;
        this.business = business;
        
        for(Organization org : enterprise.getOrganizationDirectory().getOrganizationList())   {
            if(org instanceof PatientOrganization)
                patientOrganization = (PatientOrganization)org;
            else if(org instanceof ReceptionistOrganization)
                receptionistOrganization = (ReceptionistOrganization)org;
                
        }
        
        recLabel.setText(("Receptionist Name: " + userAccount.getUsername()));
        hospitalLabel.setText("Hospital Name: " + enterprise.getName() );
        
        populatePatientCombo();
    }
    
    public void populatePatientCombo()  {
        patientComboBox.removeAllItems();
        for (Person person : patientOrganization.getPersonDirectory().getPersonList()){
                patientComboBox.addItem(person);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        goBtn = new javax.swing.JButton();
        patientComboBox = new javax.swing.JComboBox();
        enterpriseLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        recLabel = new javax.swing.JLabel();
        hospitalLabel = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        goBtn.setText("Go >>");
        goBtn.setToolTipText("Add Patient in Queue");
        goBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goBtnActionPerformed(evt);
            }
        });
        add(goBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 431, -1, -1));

        patientComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        patientComboBox.setToolTipText("Patient List");
        patientComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientComboBoxActionPerformed(evt);
            }
        });
        add(patientComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(591, 432, 143, -1));

        enterpriseLabel.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        enterpriseLabel.setText("Select Patient:");
        add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(478, 431, -1, 33));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel1.setText("OPT TICKET DASHBOARD");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 300, -1, -1));

        jButton1.setText("Current Appointments");
        jButton1.setToolTipText("List of all the waiting Patients");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(641, 502, -1, -1));

        recLabel.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        recLabel.setText("jLabel2");
        add(recLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(478, 344, -1, -1));

        hospitalLabel.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        hospitalLabel.setText("jLabel2");
        add(hospitalLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(478, 384, -1, -1));

        backBtn.setText("<< Back");
        backBtn.setToolTipText("Go to Previous Page");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(478, 502, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon("/Users/hpanjwani/Documents/NEU/1st Sem/5100 AED Lab/panjwani_hari_001664735/Project/images/Reception.jpg")); // NOI18N
        jLabel2.setText("\n\n");
        jLabel2.setToolTipText("Receptionist Dashboard");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 284));
    }// </editor-fold>//GEN-END:initComponents

    private void patientComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_patientComboBoxActionPerformed

    private void goBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goBtnActionPerformed
        // TODO add your handling code here:
        Patient patient = (Patient) patientComboBox.getSelectedItem();      
        
        AppointmentWaitingListPanel receptionWorkAreaPanel = new AppointmentWaitingListPanel(userProcessContainer, userAccount, receptionistOrganization, enterprise, patient);
        userProcessContainer.add("ReceptionWorkAreaPanel", receptionWorkAreaPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_goBtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Patient patient = null;
        AppointmentWaitingListPanel receptionWorkAreaPanel = new AppointmentWaitingListPanel(userProcessContainer, userAccount, receptionistOrganization, enterprise, patient);
        userProcessContainer.add("ReceptionWorkAreaPanel", receptionWorkAreaPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JButton goBtn;
    private javax.swing.JLabel hospitalLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JComboBox patientComboBox;
    private javax.swing.JLabel recLabel;
    // End of variables declaration//GEN-END:variables
}
