package configuration;
// Generated Feb 29, 2016 9:29:52 PM by Hibernate Tools 4.3.1



/**
 * Newsalesorder generated by hbm2java
 */
public class Newsalesorder  implements java.io.Serializable {


     private String salesOrderId;
     private String revisionNumber;
     private String orderDate;
     private String dueDate;
     private String shipDate;
     private String status;
     private String onlineOrderFlag;
     private String salesOrderNumber;
     private String purchaseOrderNumber;
     private String accountNumber;
     private String customerId;
     private String salesPersonId;
     private String territoryId;
     private String billToAddressId;
     private String shipToAddressId;
     private String shipMethodId;
     private String creditCardId;
     private String creditCardApprovalCode;
     private String currencyRateId;
     private String subTotal;
     private String taxAmt;
     private String freight;
     private String totalDue;
     private String comment;
     private String modifiedDate;

    public Newsalesorder() {
    }

	
    public Newsalesorder(String salesOrderId) {
        this.salesOrderId = salesOrderId;
    }
    public Newsalesorder(String salesOrderId, String revisionNumber, String orderDate, String dueDate, String shipDate, String status, String onlineOrderFlag, String salesOrderNumber, String purchaseOrderNumber, String accountNumber, String customerId, String salesPersonId, String territoryId, String billToAddressId, String shipToAddressId, String shipMethodId, String creditCardId, String creditCardApprovalCode, String currencyRateId, String subTotal, String taxAmt, String freight, String totalDue, String comment, String modifiedDate) {
       this.salesOrderId = salesOrderId;
       this.revisionNumber = revisionNumber;
       this.orderDate = orderDate;
       this.dueDate = dueDate;
       this.shipDate = shipDate;
       this.status = status;
       this.onlineOrderFlag = onlineOrderFlag;
       this.salesOrderNumber = salesOrderNumber;
       this.purchaseOrderNumber = purchaseOrderNumber;
       this.accountNumber = accountNumber;
       this.customerId = customerId;
       this.salesPersonId = salesPersonId;
       this.territoryId = territoryId;
       this.billToAddressId = billToAddressId;
       this.shipToAddressId = shipToAddressId;
       this.shipMethodId = shipMethodId;
       this.creditCardId = creditCardId;
       this.creditCardApprovalCode = creditCardApprovalCode;
       this.currencyRateId = currencyRateId;
       this.subTotal = subTotal;
       this.taxAmt = taxAmt;
       this.freight = freight;
       this.totalDue = totalDue;
       this.comment = comment;
       this.modifiedDate = modifiedDate;
    }
   
    public String getSalesOrderId() {
        return this.salesOrderId;
    }
    
    public void setSalesOrderId(String salesOrderId) {
        this.salesOrderId = salesOrderId;
    }
    public String getRevisionNumber() {
        return this.revisionNumber;
    }
    
    public void setRevisionNumber(String revisionNumber) {
        this.revisionNumber = revisionNumber;
    }
    public String getOrderDate() {
        return this.orderDate;
    }
    
    public void setOrderDate(String orderDate) {
        this.orderDate = orderDate;
    }
    public String getDueDate() {
        return this.dueDate;
    }
    
    public void setDueDate(String dueDate) {
        this.dueDate = dueDate;
    }
    public String getShipDate() {
        return this.shipDate;
    }
    
    public void setShipDate(String shipDate) {
        this.shipDate = shipDate;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public String getOnlineOrderFlag() {
        return this.onlineOrderFlag;
    }
    
    public void setOnlineOrderFlag(String onlineOrderFlag) {
        this.onlineOrderFlag = onlineOrderFlag;
    }
    public String getSalesOrderNumber() {
        return this.salesOrderNumber;
    }
    
    public void setSalesOrderNumber(String salesOrderNumber) {
        this.salesOrderNumber = salesOrderNumber;
    }
    public String getPurchaseOrderNumber() {
        return this.purchaseOrderNumber;
    }
    
    public void setPurchaseOrderNumber(String purchaseOrderNumber) {
        this.purchaseOrderNumber = purchaseOrderNumber;
    }
    public String getAccountNumber() {
        return this.accountNumber;
    }
    
    public void setAccountNumber(String accountNumber) {
        this.accountNumber = accountNumber;
    }
    public String getCustomerId() {
        return this.customerId;
    }
    
    public void setCustomerId(String customerId) {
        this.customerId = customerId;
    }
    public String getSalesPersonId() {
        return this.salesPersonId;
    }
    
    public void setSalesPersonId(String salesPersonId) {
        this.salesPersonId = salesPersonId;
    }
    public String getTerritoryId() {
        return this.territoryId;
    }
    
    public void setTerritoryId(String territoryId) {
        this.territoryId = territoryId;
    }
    public String getBillToAddressId() {
        return this.billToAddressId;
    }
    
    public void setBillToAddressId(String billToAddressId) {
        this.billToAddressId = billToAddressId;
    }
    public String getShipToAddressId() {
        return this.shipToAddressId;
    }
    
    public void setShipToAddressId(String shipToAddressId) {
        this.shipToAddressId = shipToAddressId;
    }
    public String getShipMethodId() {
        return this.shipMethodId;
    }
    
    public void setShipMethodId(String shipMethodId) {
        this.shipMethodId = shipMethodId;
    }
    public String getCreditCardId() {
        return this.creditCardId;
    }
    
    public void setCreditCardId(String creditCardId) {
        this.creditCardId = creditCardId;
    }
    public String getCreditCardApprovalCode() {
        return this.creditCardApprovalCode;
    }
    
    public void setCreditCardApprovalCode(String creditCardApprovalCode) {
        this.creditCardApprovalCode = creditCardApprovalCode;
    }
    public String getCurrencyRateId() {
        return this.currencyRateId;
    }
    
    public void setCurrencyRateId(String currencyRateId) {
        this.currencyRateId = currencyRateId;
    }
    public String getSubTotal() {
        return this.subTotal;
    }
    
    public void setSubTotal(String subTotal) {
        this.subTotal = subTotal;
    }
    public String getTaxAmt() {
        return this.taxAmt;
    }
    
    public void setTaxAmt(String taxAmt) {
        this.taxAmt = taxAmt;
    }
    public String getFreight() {
        return this.freight;
    }
    
    public void setFreight(String freight) {
        this.freight = freight;
    }
    public String getTotalDue() {
        return this.totalDue;
    }
    
    public void setTotalDue(String totalDue) {
        this.totalDue = totalDue;
    }
    public String getComment() {
        return this.comment;
    }
    
    public void setComment(String comment) {
        this.comment = comment;
    }
    public String getModifiedDate() {
        return this.modifiedDate;
    }
    
    public void setModifiedDate(String modifiedDate) {
        this.modifiedDate = modifiedDate;
    }




}


