package com.books.pojo;
// Generated Mar 3, 2016 12:20:09 AM by Hibernate Tools 4.3.1



/**
 * Books generated by hbm2java
 */
public class Books  implements java.io.Serializable {


     private String isbn;
     private String title;
     private String author;
     private Float price;

    public Books() {
    }

	
    public Books(String isbn) {
        this.isbn = isbn;
    }
    public Books(String isbn, String title, String author, Float price) {
       this.isbn = isbn;
       this.title = title;
       this.author = author;
       this.price = price;
    }
   
    public String getIsbn() {
        return this.isbn;
    }
    
    public void setIsbn(String isbn) {
        this.isbn = isbn;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getAuthor() {
        return this.author;
    }
    
    public void setAuthor(String author) {
        this.author = author;
    }
    public Float getPrice() {
        return this.price;
    }
    
    public void setPrice(Float price) {
        this.price = price;
    }




}


