/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.StoreAdminRole;

import Business.Drug;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author hpanjwani
 */
public class EditDrugDetailsJPanel extends javax.swing.JPanel {
    
    private JPanel userProcessContainer;
    private Drug drug;
    /**
     * Creates new form EditDrugDetais
     */
    public EditDrugDetailsJPanel(JPanel userProcessContainer, Drug drug) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.drug = drug;
        
        idTextField.setText(String.valueOf(drug.getDrugID()));
        nameTextField.setText(drug.getDrugName());
        mrpTextField.setText(String.valueOf(drug.getPrice()));
        listPriceTextField.setText(String.valueOf(drug.getListPrice()));
        availTextField.setText(String.valueOf(drug.getAvail()));
        
        serialNumberTextField.setText(String.valueOf(drug.getSerialNumber()));
        expDateTextField.setText(drug.getExpDate());
        saltNameTextField.setText(drug.getSaltName());
        stabilityTextField.setText(drug.getStability());
        strengthTextField.setText(drug.getStrength());
        colorTextField.setText(drug.getColor());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        idTextField = new javax.swing.JTextField();
        nameTextField = new javax.swing.JTextField();
        serialNumberTextField = new javax.swing.JTextField();
        mrpTextField = new javax.swing.JTextField();
        listPriceTextField = new javax.swing.JTextField();
        availTextField = new javax.swing.JTextField();
        saltNameTextField = new javax.swing.JTextField();
        stabilityTextField = new javax.swing.JTextField();
        strengthTextField = new javax.swing.JTextField();
        colorTextField = new javax.swing.JTextField();
        updateBtn = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        expDateTextField = new javax.swing.JTextField();
        saveBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setText("EDIT DRUG DETAILS");

        jLabel2.setText("Drug ID:");

        jLabel3.setText("Drug Name:");

        jLabel4.setText("Serial Number:");

        jLabel5.setText("Market Price:");

        jLabel6.setText("List Price:");

        jLabel7.setText("Availability:");

        jLabel8.setText("Salt Name:");

        jLabel9.setText("Stability:");

        jLabel10.setText("Strength:");

        jLabel11.setText("Color:");

        idTextField.setEditable(false);
        idTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idTextFieldActionPerformed(evt);
            }
        });

        nameTextField.setEditable(false);

        serialNumberTextField.setEditable(false);

        mrpTextField.setEditable(false);
        mrpTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mrpTextFieldActionPerformed(evt);
            }
        });

        listPriceTextField.setEditable(false);
        listPriceTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listPriceTextFieldActionPerformed(evt);
            }
        });

        availTextField.setEditable(false);

        saltNameTextField.setEditable(false);

        stabilityTextField.setEditable(false);

        strengthTextField.setEditable(false);

        colorTextField.setEditable(false);

        updateBtn.setText("Update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        jLabel12.setText("Expiration Date:");

        expDateTextField.setEditable(false);

        saveBtn.setText("Save");
        saveBtn.setEnabled(false);
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        backBtn.setText("<< Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel12)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jLabel1))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(backBtn)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(saveBtn)
                            .addGap(48, 48, 48)
                            .addComponent(updateBtn))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addComponent(jLabel6)
                                .addComponent(jLabel7)
                                .addComponent(jLabel8)
                                .addComponent(jLabel9)
                                .addComponent(jLabel10)
                                .addComponent(jLabel11))
                            .addGap(167, 167, 167)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(idTextField)
                                    .addComponent(nameTextField)
                                    .addComponent(expDateTextField)
                                    .addComponent(serialNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(mrpTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(listPriceTextField)
                                    .addComponent(availTextField)
                                    .addComponent(saltNameTextField)
                                    .addComponent(stabilityTextField)
                                    .addComponent(strengthTextField)
                                    .addComponent(colorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(264, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(idTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(serialNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(expDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(mrpTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(listPriceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(availTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(saltNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(stabilityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(strengthTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(colorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(updateBtn)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(saveBtn)
                        .addComponent(backBtn)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void idTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idTextFieldActionPerformed

    private void mrpTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mrpTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mrpTextFieldActionPerformed

    private void listPriceTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listPriceTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listPriceTextFieldActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:

        serialNumberTextField.setEditable(true);
        expDateTextField.setEditable(true);
        saltNameTextField.setEditable(true);
        stabilityTextField.setEditable(true);
        strengthTextField.setEditable(true);
        colorTextField.setEditable(true);

        saveBtn.setEnabled(true);
    }//GEN-LAST:event_updateBtnActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        // TODO add your handling code here:

        if(serialNumberTextField.getText().trim().isEmpty())  {
            JOptionPane.showMessageDialog(this, "Serial Number cannot be empty!", "WARNING", JOptionPane.WARNING_MESSAGE);
            serialNumberTextField.setBackground(Color.red);
        }
        else if (!serialNumberTextField.getText().matches("[0-9]*")){
            JOptionPane.showMessageDialog(this, "Please enter valid Serial Number!", "Error", JOptionPane.OK_OPTION);
            serialNumberTextField.setBackground(Color.red);
        }
        else if(expDateTextField.getText().trim().isEmpty())  {
            JOptionPane.showMessageDialog(this, "Expiration Date cannot be empty!", "WARNING", JOptionPane.WARNING_MESSAGE);
            expDateTextField.setBackground(Color.red);
        }
        else if(saltNameTextField.getText().trim().isEmpty())  {
            JOptionPane.showMessageDialog(this, "Salt Name cannot be empty!", "WARNING", JOptionPane.WARNING_MESSAGE);
            saltNameTextField.setBackground(Color.red);
        }
        else if (!saltNameTextField.getText().matches("[a-zA-Z]*")){
            JOptionPane.showMessageDialog(this, "Please enter valid Salt Name for Drug!", "Error", JOptionPane.OK_OPTION);
            saltNameTextField.setBackground(Color.red);
        }
        else if(stabilityTextField.getText().trim().isEmpty())  {
            JOptionPane.showMessageDialog(this, "Stability cannot be empty!", "WARNING", JOptionPane.WARNING_MESSAGE);
            stabilityTextField.setBackground(Color.red);
        }
        else if (!stabilityTextField.getText().matches("[a-zA-Z]*")){
            JOptionPane.showMessageDialog(this, "Please enter valid Stability for Drug!", "Error", JOptionPane.OK_OPTION);
            stabilityTextField.setBackground(Color.red);
        }
        else if(strengthTextField.getText().trim().isEmpty())  {
            JOptionPane.showMessageDialog(this, "Strength cannot be empty!", "WARNING", JOptionPane.WARNING_MESSAGE);
            strengthTextField.setBackground(Color.red);
        }
        else if (!strengthTextField.getText().matches("[a-zA-Z]*")){
            JOptionPane.showMessageDialog(this, "Please enter valid Strength for Drug!", "Error", JOptionPane.OK_OPTION);
            strengthTextField.setBackground(Color.red);
        }
        else if(colorTextField.getText().trim().isEmpty())  {
            JOptionPane.showMessageDialog(this, "Color cannot be empty!", "WARNING", JOptionPane.WARNING_MESSAGE);
            colorTextField.setBackground(Color.red);
        }
        else if (!colorTextField.getText().matches("[a-zA-Z]*")){
            JOptionPane.showMessageDialog(this, "Please enter valid Color for Drug!", "Error", JOptionPane.OK_OPTION);
            colorTextField.setBackground(Color.red);
        }
        else    {
        
            drug.setSerialNumber(Integer.parseInt(serialNumberTextField.getText()));
            drug.setExpDate(expDateTextField.getText());
            drug.setSaltName(saltNameTextField.getText());
            drug.setStability(stabilityTextField.getText());
            drug.setStrength(strengthTextField.getText());
            drug.setColor(colorTextField.getText());

            JOptionPane.showMessageDialog(this, "Drug details has been updated successfully", "INFORMATION", JOptionPane.INFORMATION_MESSAGE);
            resetFields();
        }
    }//GEN-LAST:event_saveBtnActionPerformed
    
    public void resetFields()   {
        serialNumberTextField.setText("");
        serialNumberTextField.setBackground(Color.white);
        expDateTextField.setText("");
        expDateTextField.setBackground(Color.white);
        saltNameTextField.setText("");
        saltNameTextField.setBackground(Color.white);
        stabilityTextField.setText("");
        stabilityTextField.setBackground(Color.white);
        strengthTextField.setText("");
        strengthTextField.setBackground(Color.white);
        colorTextField.setText("");
        colorTextField.setBackground(Color.white);
    }
    
    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:

        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ManageDrugInventoryJPanel generateReport = (ManageDrugInventoryJPanel) component;
        generateReport.populateStoreTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField availTextField;
    private javax.swing.JButton backBtn;
    private javax.swing.JTextField colorTextField;
    private javax.swing.JTextField expDateTextField;
    private javax.swing.JTextField idTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField listPriceTextField;
    private javax.swing.JTextField mrpTextField;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JTextField saltNameTextField;
    private javax.swing.JButton saveBtn;
    private javax.swing.JTextField serialNumberTextField;
    private javax.swing.JTextField stabilityTextField;
    private javax.swing.JTextField strengthTextField;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
