/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.StoreAdminRole;

import Business.Drug;
import Business.Store;
import Business.StoreCatalog;
import Business.Supplier;
import Business.SupplierCatalog;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hpanjwani
 */
public class GenerateReportJPanel extends javax.swing.JPanel {
    
    private JPanel userProcessContainer;
    private SupplierCatalog supplierCatalog;
    private StoreCatalog storeCatalog;
    private Store store;
    private ArrayList<Drug> drugNotAvailable;
    private int threshold = 50;
    
    /**
     * Creates new form ReportJPanel
     */
    public GenerateReportJPanel(JPanel userProcessContainer, SupplierCatalog supplierCatalog, StoreCatalog storeCatalog) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.storeCatalog = storeCatalog;
        this.supplierCatalog = supplierCatalog;
        
//        locationLabel.setText(store.getLocation());
//        nameLabel.setText(store.getStoreName());
//        streetLabel.setText(store.getStreet());
//        cityLabel.setText(store.getCity());
       
        populateLocation();
        //populateReportTable();
    }
    
    public void populateLocation()  {
        locationComboBox.removeAllItems();
        
        for(Store store : storeCatalog.getStoreCatalog())   {
            locationComboBox.addItem(store);
        }
        //populateReportTable();
    }
    
    public void populateReportTable()    {
        
        drugNotAvailable = new ArrayList<>();
        
        store = (Store)locationComboBox.getSelectedItem();
        
        locationLabel.setText(store.getLocation());
        nameLabel.setText(store.getStoreName());
        streetLabel.setText(store.getStreet());
        cityLabel.setText(store.getCity());
        
        DefaultTableModel dtm = (DefaultTableModel)reportTable.getModel();
        dtm.setRowCount(0);
        Object[] row = new Object[5];
        
        
        for(Supplier supplier : supplierCatalog.getSupplierCatalog())   {
            for(Drug drug : supplier.getDrugCatalog().getDrugList())    {
                drugNotAvailable.add(drug);
            }
        }
        
        for(Drug storeDrug : store.getDrugCatalog().getDrugList())  {
            for(int i=0; i < drugNotAvailable.size(); i++)  {
                if(storeDrug.getDrugID()== drugNotAvailable.get(i).getDrugID()) {
                    drugNotAvailable.remove(i);
                }
            }
        }
        
        for(Drug drug : drugNotAvailable)   {
            row[0] = drug.getDrugID();
            row[1] = drug;
            row[2] = drug.getListPrice();
            row[3] = drug.getAvail();
            row[4] = "Not Available in Store";
            dtm.addRow(row);
        }
        
        for(Drug storeDrug : store.getDrugCatalog().getDrugList())   {
            if(storeDrug.getAvail() < threshold)   {
                row[0] = storeDrug.getDrugID();
                row[1] = storeDrug;
                row[2] = storeDrug.getListPrice();
                row[3] = storeDrug.getAvail();
                row[4] = "Below Threshold Value";
                dtm.addRow(row);
            }   
        }
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        locationLabel = new javax.swing.JLabel();
        cityLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        streetLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        reportTable = new javax.swing.JTable();
        backBtn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        locationComboBox = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("INVENTORY REPORT");

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setText("Store Name:");

        nameLabel.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        nameLabel.setText("jLabel2");

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel2.setText("Store Location:");

        locationLabel.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        locationLabel.setText("jLabel4");

        cityLabel.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        cityLabel.setText("jLabel2");

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel5.setText("Store City:");

        streetLabel.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        streetLabel.setText("jLabel2");

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel3.setText("Store Street:");

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel6.setText("Threshold Value: 50");

        reportTable.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        reportTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Drug ID", "Drug Name", "Price", "Availibilty", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(reportTable);
        if (reportTable.getColumnModel().getColumnCount() > 0) {
            reportTable.getColumnModel().getColumn(4).setPreferredWidth(300);
        }

        backBtn.setText("<< Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Location");

        locationComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                locationComboBoxActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("DRUG INVENTORY REPORT");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(nameLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(streetLabel)))
                        .addGap(112, 112, 112)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(cityLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(locationLabel))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(locationComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6))
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 686, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backBtn)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(268, 268, 268)
                        .addComponent(jLabel4)))
                .addGap(0, 152, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(locationComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nameLabel)
                    .addComponent(jLabel2)
                    .addComponent(locationLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(streetLabel))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(cityLabel)))
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(backBtn)
                .addContainerGap(40, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backBtnActionPerformed

    private void locationComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_locationComboBoxActionPerformed
        // TODO add your handling code here:
        populateReportTable();
    }//GEN-LAST:event_locationComboBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel cityLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox locationComboBox;
    private javax.swing.JLabel locationLabel;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTable reportTable;
    private javax.swing.JLabel streetLabel;
    // End of variables declaration//GEN-END:variables
}
